name: Create coverage badges

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test
      - id: read_coverage
        name: Read coverage
        run: |
          content=`cat ./coverage/coverage-summary.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo '::set-output name=coverage.json::$content'

      - name: Create badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gitsID: ded8feb6e79c379a8e04b613ced59d28
          filename: coverage.json
          label: Coverage
          message: ${{ fromJson(steps.read_coverage.outputs.coverage.json).total.lines.pct }}
          valColorRange: ${{ fromJson(steps.read_coverage.outputs.coverage.json).total.lines.pct }}
          maxColorRange: 100
          minColorRange: 0
